In [2]:
import numpy as np

### 1. 넘파이를 사용하여 다음과 같은 행렬을 만들고, 이 배열에서 값 70을 인덱싱하세요.  (3.1 - 연습문제 1 변형)
10 20 30 40 <br>
50 60 70 80 <br>

In [3]:
# 밑에 코드 작성
c=np.array([[10,20,30,40],[50,60,70,80]])
c


array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [10]:
a=c[1,2]
print(a)

70


### 2. 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하라. (연습문제 3.3.2)

In [16]:
v = np.array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])

# 밑에 코드 작성
import numpy as np

v= np.array([[ 1, 2, 3, 4],
[ 46, 99, 100, 71],
[ 81, 59, 90, 100]])

english_ranking = np.argsort(v[1,:])

print(v[:,english_ranking])

[[  1   4   2   3]
 [ 46  71  99 100]
 [ 81 100  59  90]]


### 3. 코사인 유사도 함수 구현하기

유사도 계산 공식
cosine_similarity = dot_product / (magnitude1 * magnitude2)

In [23]:
from numpy.linalg import norm # np.linalg.norm() 함수는 배열의 크기(norm)를 계산

def cos_sim(A, B):
    dot_product = np.dot(A, B) # np.dot() 함수는 두 배열의 내적을 계산
    norm_A = norm(A)
    norm_B = norm(B)
    similarity = dot_product / (norm_A * norm_B)
    return similarity

doc1 = np.array([0, 1, 1, 1])
doc2 = np.array([1, 0, 1, 1])

result = round(cos_sim(doc1, doc2), 2)
print(result)

0.67


- 정답 : 0.67

## 4,5번 문제 : 붓꽃 데이터 활용 

### 4. 붓꽃들의 변수별 가중치를 통해 전체 붓꽃 가중평균 구하기

- 변수별 가중치
    - 꽃받침의 길이 : 0.3, 꽃받침의 폭 : 0.2, 꽃잎의 길이 : 0.25, 꽃잎의 폭 : 0.25

In [35]:
pip install scikit-learn

  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/4e/ba/ce9bd1cd4953336a0e213b29cb80bb11816f2a93de8c99f88ef0b446ad0c/scikit_learn-1.3.2-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for scipy>=1.5.0 from https://files.pythonhosted.org/packages/81/d7/d2537d51efb692d0c411e64267ba349e7668d40f5bc73cefe78ccd650dcd/scipy-1.11.3-cp311-cp311-win_amd64.whl.metadata
     ---------------------------------------- 0.0/60.4 kB ? eta -:--:--
     ---------------------------------------- 60.4/60.4 kB 3.1 MB/s eta 0:00:00
  Obtaining dependency information for joblib>=1.1.1 from https://files.pythonhosted.org/packages/10/40/d551139c85db202f1f384ba8bcf96aca2f329440a844f924c8a0040b6d02/joblib-1.3.2-py3-none-any.whl.metadata
  Obtaining dependency information for threadpoolctl>=2.0.0 from https://files.pythonhosted.org/packages/81/12/fd4dea011af9d69e1cad05c75f3f7202cdcbeac9b712eea58ca779a72865/threadpoolctl-3.2.0-py3-none-any.whl.metad


[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [49]:
from sklearn.datasets import load_iris

iris = load_iris() # 붓꽃 데이터 로드
X = iris.data

def weighted_average(data):
        # 변수별 가중치 정의
    weights = np.array([0.3, 0.2, 0.25, 0.25])
    
    # 가중평균 계산
    weighted_avg = np.dot(data, weights)
    
    return np.round(weighted_avg, 4)

result = weighted_average(X)
print(result)

[2.63  2.47  2.425 2.425 2.62  2.925 2.485 2.605 2.3   2.49  2.785 2.57
 2.415 2.19  2.89  3.065 2.825 2.655 2.97  2.74  2.775 2.745 2.4   2.74
 2.645 2.55  2.68  2.685 2.64  2.5   2.51  2.775 2.78  2.89  2.515 2.49
 2.725 2.565 2.295 2.635 2.6   2.21  2.335 2.75  2.865 2.465 2.74  2.42
 2.755 2.56  4.265 4.06  4.29  3.435 4.035 3.72  4.125 3.025 4.035 3.425
 3.025 3.795 3.49  3.935 3.485 4.08  3.78  3.555 3.8   3.43  4.06  3.715
 3.99  3.865 3.9   4.03  4.15  4.285 3.88  3.355 3.355 3.305 3.555 4.015
 3.72  4.005 4.18  3.775 3.63  3.475 3.57  3.93  3.56  3.035 3.595 3.66
 3.665 3.84  3.055 3.62  4.675 4.03  4.73  4.32  4.55  5.055 3.52  4.795
 4.41  5.03  4.365 4.26  4.54  3.96  4.175 4.46  4.375 5.295 5.13  3.865
 4.71  3.965 5.045 4.105 4.62  4.75  4.07  4.105 4.405 4.61  4.78  5.23
 4.43  4.1   4.1   5.01  4.57  4.365 4.05  4.565 4.63  4.54  4.03  4.73
 4.72  4.485 4.115 4.35  4.465 4.095]


- 정답 <br>
3.6038

### 5. 붓꽃들의 각 변수별 기술통계량 구하기 : 평균, 중앙값, 표준편차

- 소수점 둘째자리까지
- 2차원 리스트의 형태로 반환
    - [[변수 1의 평균, 변수 1의 중앙값, 변수 1의 표준편차], ..., [변수 4의 평균, 변수 4의 중앙값, 변수 4의 표준편차]]

In [46]:
def stats(X):
    # Transpose
    X_t = X.T

    result = []

    for variable in X_t:
        mean_value = np.mean(variable)
        median_value = np.median(variable)
        std_deviation = np.std(variable, ddof=0)
        
        result.append([round(mean_value, 2), round(median_value, 2), round(std_deviation, 2)])
    
    return result

X = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

result = stats(X)
print(result)

[[5.0, 5.0, 3.27], [6.0, 6.0, 3.27], [7.0, 7.0, 3.27], [8.0, 8.0, 3.27]]


- 정답 <br>
[[5.84, 5.8, 0.83], [3.06, 3.0, 0.43], [3.76, 4.35, 1.76], [1.2, 1.3, 0.76]]

- numpy 공홈 : https://numpy.org/
- numpy ex100 : https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb